Show subtotal and empty donation, total on invoices with hide_total=t…
hitobito/hitobito_sww pull request #111
Opened 2023-03-07 16:51 UTC by daniel-illi

fixes #51

2023-03-13 07:30 UTC, TheWalkingLeek requested changes
Paar kleine Sachen :)

2023-03-13 07:30 UTC, TheWalkingLeek commented on app/domain/sww/export/pdf/invoice/articles.rb
> +      [I18n.t('invoices.pdf.cost'), decorated.cost],
Machts vielleicht noch Sinn hier das `total_vat` einzufügen? Insbesondere da Zwischenbeitrag + MwSt. = Subtotal

2023-03-13 07:30 UTC, TheWalkingLeek commented on app/views/invoices/_form_sww.html.haml
> -= f.labeled_input_field :membership_card, caption: t('.membership_card_caption')
huh? Sollte das weg?

2023-03-13 07:30 UTC, TheWalkingLeek commented on spec/domain/sww/export/pdf/invoice_spec.rb
> +    it 'renders total when hite_total=false' do
```suggestion
    it 'renders total when hide_total=false' do
```

2023-03-24 15:19 UTC, daniel-illi commented on app/views/invoices/_form_sww.html.haml
> -= f.labeled_input_field :membership_card, caption: t('.membership_card_caption')
not really....

2023-03-24 15:27 UTC, merged