Feature/hitobito sww#190
hitobito/hitobito_sww pull request #220
Opened 2024-11-05 16:37 UTC by diegosteiner

refs #190 

Muss zusammen mit dem PR im core gemerged werden

2024-11-07 12:59 UTC, TheWalkingLeek requested changes

2024-11-07 12:59 UTC, TheWalkingLeek commented on app/helpers/sww/layout_helper.rb
> +        params[:oauth].present?
Das sollte invertiert sein oder? Aktuell wird bei Oauth das Logo angezeigt, beim normalen login nicht

2024-11-12 09:03 UTC, diegosteiner commented on app/helpers/sww/layout_helper.rb
> +        params[:oauth].present?
Gut gesehen! Danke. Habe dafür noch eine spec nachgeliefert, bitte nochmals anschauen.

2024-11-12 10:37 UTC, TheWalkingLeek approved these changes

2024-11-21 07:23 UTC, merged