Add custom address offsets
hitobito/hitobito_sww pull request #74
Opened 2022-09-16 06:36 UTC by TheWalkingLeek

Refs: #68 
Merge first: https://github.com/hitobito/hitobito/pull/1842

2022-09-19 12:55 UTC, carlobeltrame requested changes
Muss das noch ausführlich von Hand testen, aber hier schon mal was mir am Code auffällt

2022-09-19 12:55 UTC, carlobeltrame commented on config/locales/models.sww.de.yml
> +          membership_card: Mitgliederkarten
```suggestion
          membership_card: Mitgliederausweise
```

2022-09-19 12:55 UTC, carlobeltrame commented on app/domain/sww/export/pdf/address_renderers.rb
> +      y_coords ||= cursor
Als Offset müsste sich die Berechnung hier trotzdem noch an `cursor` orientieren oder nicht? So wie es aktuell implementiert ist machts einen Unterschied ob ich ins Feld 0 eintrage oder es leer lasse. Das sollte nach meinem Verständnis nicht so sein.

2022-09-19 13:10 UTC, TheWalkingLeek commented on app/domain/sww/export/pdf/address_renderers.rb
> +      y_coords ||= cursor
Nein? Und wenn ich wirklich meine Addresse bei 0 cm vom Rand haben will?
Also meine Absicht war es, wenn ein Wert im Setting gegeben ist, immer dieses zu nehmen. Wenn nicht, benutzen wir die vorherige Logik.
Das Offset muss auch nichts vom cursor wissen, weil der cursor gar nicht verschoben wird um die Addressen zu schreiben. Sprich wir holen die absoluten Koordinaten der Address-Box auf der ganzen Page

2022-09-20 18:46 UTC, kronn approved these changes

2022-09-20 18:46 UTC, kronn commented on app/domain/sww/export/pdf/address_renderers.rb
> +      y_coords ||= cursor
Ich habe `offset` mal zu `position` umbenannt, um das deutlicher zu machen. Für den Benutzer ist "Abstand" trotz aller Semantik vermutlich am ehesten vom Seitenrand zu messen.

2022-09-20 18:47 UTC, merged